# Generated by Django 4.0.5 on 2022-06-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_csvupload_csv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvupload',
            name='csv_file',
            field=models.FileField(upload_to='H:/Interview/SP/spproject/home/upload/'),
        ),
    ]
